language: generic
notifications:
  email: false

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
        - os: linux
          sudo: required
        #- os: osx
        #  osx_image: xcode7

install:
  - bash ./installation_script.sh

before_script:
  #add conda path to the system. For some reason it does not work if it is done in the installation script.
  - ls /home/travis/miniconda/bin
  - export PATH=/home/travis/miniconda/bin:$PATH

script:
  - which python3 
  - python3 ./installation/installation_test.py #test installation libraries
  - python3 ./Tests/run_tests.py #run tests